# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_post_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_imag',
            field=models.FileField(blank=True, upload_to='./upload/'),
        ),
    ]
