# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_post_post_imag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='district',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='fact',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_imag',
            field=models.FileField(blank=True, upload_to='./cases/static/imgs/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='predict',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='protection',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_in',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='village',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='work_site',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
