# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20170711_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='damage_des',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='measures',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='room',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='service',
            name='describe',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='worker',
            name='num',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='praise',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='worker',
            name='tele',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
