# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20170711_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(blank=True, max_length=70)),
                ('path', models.FileField(blank=True, upload_to='./cases/static/imgs/')),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Post')),
            ],
        ),
    ]
