# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20170718_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(blank=True, max_length=70)),
                ('path', models.FileField(blank=True, upload_to='./cases/static/imgs/')),
            ],
        ),
        migrations.CreateModel(
            name='StartInImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(blank=True, max_length=70)),
                ('path', models.FileField(blank=True, upload_to='./cases/static/imgs/')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSiteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(blank=True, max_length=70)),
                ('path', models.FileField(blank=True, upload_to='./cases/static/imgs/')),
            ],
        ),
        migrations.RenameModel(
            old_name='FirstImage',
            new_name='FinishImage',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='first_image',
            new_name='finish_image',
        ),
        migrations.AddField(
            model_name='post',
            name='protection_image',
            field=models.ManyToManyField(blank=True, to='cases.ProtectionImage'),
        ),
        migrations.AddField(
            model_name='post',
            name='start_image',
            field=models.ManyToManyField(blank=True, to='cases.StartInImage'),
        ),
        migrations.AddField(
            model_name='post',
            name='work_site_image',
            field=models.ManyToManyField(blank=True, to='cases.WorkSiteImage'),
        ),
    ]
