# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20170718_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='post',
            name='protection',
        ),
        migrations.RemoveField(
            model_name='post',
            name='start_in',
        ),
        migrations.RemoveField(
            model_name='post',
            name='work_site',
        ),
    ]
