# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_auto_20170718_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='start_image',
            new_name='start_in_image',
        ),
    ]
