# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20170718_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Scheme'),
        ),
    ]
