# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_auto_20170719_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='finish_image',
            field=models.ManyToManyField(blank=True, null=True, to='cases.FinishImage'),
        ),
        migrations.AlterField(
            model_name='post',
            name='protection_image',
            field=models.ManyToManyField(blank=True, null=True, to='cases.ProtectionImage'),
        ),
        migrations.AlterField(
            model_name='post',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Service'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_in_image',
            field=models.ManyToManyField(blank=True, null=True, to='cases.StartInImage'),
        ),
        migrations.AlterField(
            model_name='post',
            name='work_site_image',
            field=models.ManyToManyField(blank=True, null=True, to='cases.WorkSiteImage'),
        ),
        migrations.AlterField(
            model_name='post',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Worker'),
        ),
    ]
