# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_auto_20170719_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startinimage',
            name='path',
            field=models.FileField(blank=True, upload_to='imgs'),
        ),
    ]
