# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_auto_20170719_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='finish_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='protection_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='start_in_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='work_site_image',
        ),
        migrations.AddField(
            model_name='startinimage',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Post'),
        ),
    ]
