# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_auto_20170720_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startinimage',
            name='path',
            field=models.FileField(blank=True, upload_to='media/imgs/'),
        ),
    ]
