# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-21 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_auto_20170721_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='protectionimage',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Post'),
        ),
        migrations.AlterField(
            model_name='protectionimage',
            name='path',
            field=models.FileField(blank=True, upload_to='media/imgs/'),
        ),
    ]
