# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_auto_20170725_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
