# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_auto_20170726_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='district',
            field=models.CharField(blank=True, choices=[('01', '朝阳区'), ('02', '通州区'), ('03', '海淀区'), ('04', '东城区'), ('05', '西城区'), ('06', '丰台区')], max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.CharField(blank=True, choices=[('01', '施工中'), ('02', '已完工')], default='01', max_length=70),
        ),
    ]
