# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_owner'),
        ('cases', '0024_auto_20170731_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Owner'),
        ),
    ]
