# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-19 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Worker'),
        ),
    ]
