# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_service_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, upload_to='media/imgs/'),
        ),
    ]
