# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0027_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='scope',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
