# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0028_service_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeInService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='media/imgs/')),
                ('name', models.CharField(blank=True, max_length=70)),
                ('price', models.PositiveIntegerField(blank=True, default=0)),
                ('describe', models.TextField(blank=True)),
                ('Service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Service')),
            ],
        ),
    ]
