# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-25 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0030_service_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='service',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
