# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0034_auto_20170904_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemeinservice',
            old_name='name_it',
            new_name='name',
        ),
    ]
