# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0029_schemeinservice'),
        ('order', '0003_auto_20170822_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Service'),
        ),
    ]
