# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='password',
            field=models.CharField(blank=True, default='111', max_length=100),
        ),
    ]
